version: '3.8'

services:
  emqx1:
    image: emqx/emqx:5.4.1
    container_name: emqx1
    environment:
      - EMQX_NODE__NAME=emqx1@emqx1.local
      - EMQX_NODE__COOKIE=secretcookie
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_CLUSTER__STATIC__SEEDS=["emqx1@emqx1.local","emqx2@emqx2.local","emqx3@emqx3.local"]
    networks:
      emqx-net:
        aliases:
          - emqx1.local
    ports:
      - "18081:18083"  # Dashboard
      - "1881:1883"    # MQTT
      - "8881:8883"    # MQTT over SSL/TLS
      - "8081:8083"    # WebSocket

  emqx2:
    image: emqx/emqx:5.4.1
    container_name: emqx2
    environment:
      - EMQX_NODE__NAME=emqx2@emqx2.local
      - EMQX_NODE__COOKIE=secretcookie
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_CLUSTER__STATIC__SEEDS=["emqx1@emqx1.local","emqx2@emqx2.local","emqx3@emqx3.local"]
    networks:
      emqx-net:
        aliases:
          - emqx2.local
    ports:
      - "28083:18083"  # Dashboard
      - "2883:1883"    # MQTT
      - "8884:8883"    # MQTT over SSL/TLS
      - "8082:8083"    # WebSocket

  emqx3:
    image: emqx/emqx:5.4.1
    container_name: emqx3
    environment:
      - EMQX_NODE__NAME=emqx3@emqx3.local
      - EMQX_NODE__COOKIE=secretcookie
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_CLUSTER__STATIC__SEEDS=["emqx1@emqx1.local","emqx2@emqx2.local","emqx3@emqx3.local"]
    networks:
      emqx-net:
        aliases:
          - emqx3.local
    ports:
      - "38083:18083"  # Dashboard
      - "3883:1883"    # MQTT
      - "8885:8883"    # MQTT over SSL/TLS
      - "8083:8083"    # WebSocket

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "1883:1883"    # MQTT load-balanced entry point
      - "8080:8080"    # HAProxy stats UI
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - emqx1
      - emqx2
      - emqx3
    networks:
      - emqx-net    
      
networks:
  emqx-net:
    driver: bridge
